-- 004_permission_defaults.sql
-- Permissões padrão por perfil

with role_permissions (perfil, recurso, acoes) as (
  values
    ('master'::public.user_role, 'dashboard', array['read']),
    ('master'::public.user_role, 'agenda', array['read','create','update','delete']),
    ('master'::public.user_role, 'pacientes', array['read','create','update','delete']),
    ('master'::public.user_role, 'anamnese', array['read','create','update']),
    ('master'::public.user_role, 'prontuarios', array['read','create','update']),
    ('master'::public.user_role, 'evolucoes', array['read','create','update']),
    ('master'::public.user_role, 'documentacao', array['read','create','update']),
    ('master'::public.user_role, 'prescricoes', array['read','create','update','delete']),
    ('master'::public.user_role, 'estoque', array['read','create','update','delete']),
    ('master'::public.user_role, 'lista-espera', array['read','create','update','delete']),
    ('master'::public.user_role, 'caixa', array['read','create','update','delete']),
    ('master'::public.user_role, 'financeiro', array['read','create','update','delete']),
    ('master'::public.user_role, 'repasse', array['read','create','update','delete']),
    ('master'::public.user_role, 'relatorios', array['read']),
    ('master'::public.user_role, 'auditoria', array['read']),
    ('master'::public.user_role, 'usuarios', array['read','create','update','delete']),
    ('master'::public.user_role, 'permissoes', array['read','create','update','delete']),
    ('master'::public.user_role, 'unidades', array['read','create','update','delete']),
    ('master'::public.user_role, 'configuracoes', array['read','update']),
    ('master'::public.user_role, 'tarefas', array['read','create','update','delete']),
    ('admin'::public.user_role, 'dashboard', array['read']),
    ('admin'::public.user_role, 'agenda', array['read']),
    ('admin'::public.user_role, 'usuarios', array['read','create','update','delete']),
    ('admin'::public.user_role, 'permissoes', array['read','create','update','delete']),
    ('admin'::public.user_role, 'unidades', array['read','create','update','delete']),
    ('admin'::public.user_role, 'caixa', array['read','create','update']),
    ('admin'::public.user_role, 'financeiro', array['read','create','update']),
    ('admin'::public.user_role, 'repasse', array['read','create','update']),
    ('admin'::public.user_role, 'relatorios', array['read']),
    ('admin'::public.user_role, 'auditoria', array['read']),
    ('admin'::public.user_role, 'configuracoes', array['read','update']),
    ('gestor'::public.user_role, 'dashboard', array['read']),
    ('gestor'::public.user_role, 'agenda', array['read','create','update']),
    ('gestor'::public.user_role, 'pacientes', array['read','create','update']),
    ('gestor'::public.user_role, 'lista-espera', array['read','create','update']),
    ('gestor'::public.user_role, 'prescricoes', array['read','create','update']),
    ('gestor'::public.user_role, 'estoque', array['read','update']),
    ('gestor'::public.user_role, 'documentacao', array['read']),
    ('gestor'::public.user_role, 'financeiro', array['read']),
    ('gestor'::public.user_role, 'repasse', array['read']),
    ('gestor'::public.user_role, 'usuarios', array['read']),
    ('gestor'::public.user_role, 'permissoes', array['read']),
    ('gestor'::public.user_role, 'unidades', array['read']),
    ('gestor'::public.user_role, 'relatorios', array['read']),
    ('gestor'::public.user_role, 'configuracoes', array['read']),
    ('recepcao'::public.user_role, 'dashboard', array['read']),
    ('recepcao'::public.user_role, 'agenda', array['read','create','update']),
    ('recepcao'::public.user_role, 'pacientes', array['read','create','update']),
    ('recepcao'::public.user_role, 'prescricoes', array['read','create']),
    ('recepcao'::public.user_role, 'estoque', array['read']),
    ('recepcao'::public.user_role, 'lista-espera', array['read','create','update']),
    ('recepcao'::public.user_role, 'caixa', array['read','create','update']),
    ('recepcao'::public.user_role, 'financeiro', array['read']),
    ('recepcao'::public.user_role, 'relatorios', array['read']),
    ('recepcao'::public.user_role, 'configuracoes', array['read']),
    ('recepcao'::public.user_role, 'tarefas', array['read','create','update']),
    ('recepcao'::public.user_role, 'usuarios', array['read']),
    ('especialista'::public.user_role, 'dashboard', array['read']),
    ('especialista'::public.user_role, 'agenda', array['read']),
    ('especialista'::public.user_role, 'pacientes', array['read']),
    ('especialista'::public.user_role, 'anamnese', array['read','create','update']),
    ('especialista'::public.user_role, 'prontuarios', array['read','create','update']),
    ('especialista'::public.user_role, 'evolucoes', array['read','create','update']),
    ('especialista'::public.user_role, 'prescricoes', array['read','create','update']),
    ('especialista'::public.user_role, 'estoque', array['read']),
    ('especialista'::public.user_role, 'documentacao', array['read','create','update']),
    ('especialista'::public.user_role, 'relatorios', array['read']),
    ('especialista'::public.user_role, 'configuracoes', array['read']),
    ('paciente'::public.user_role, 'portal.dashboard', array['read']),
    ('paciente'::public.user_role, 'portal.historico', array['read']),
    ('paciente'::public.user_role, 'portal.agendamentos', array['read','create']),
    ('paciente'::public.user_role, 'portal.cartoes', array['read','create','update','delete']),
    ('paciente'::public.user_role, 'portal.pagamentos', array['read']),
    ('paciente'::public.user_role, 'configuracoes', array['read','update'])
)
insert into public.perfil_permissoes (perfil, recurso_id, acao)
select rp.perfil, r.id, acao
from role_permissions rp
join public.recursos r on r.codigo = rp.recurso
cross join unnest(rp.acoes) as acao
on conflict (perfil, recurso_id, acao) do nothing;
